#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=1.1.0
PKG_SRCS=ftp://ftp.alsa-project.org/pub/utils/alsa-utils-$PKG_VER.tar.bz2
PKG_DESC="Audio tools"
PKG_DEPS="musl ncurses alsa-lib"

build() {
	./configure --prefix=/$PFIX \
	            --sbindir=/$PFIX/bin \
	            --mandir=/$PFIX/man \
	            --disable-nls \
	            --disable-bat \
	            --disable-xmlto \
	            --without-udev-rules-dir \
	            --with-curses=ncurses \
	            --with-asound-state-dir=/etc \
	            --with-alsactl-pidfile-dir=/run
	[ $? -ne 0 ] && return 1

	$MAKE
}

package() {
	$MAKE install
	install -D -m 644 README $DESTDIR/$PFIX/doc/alsa-utils/README
	install -m 644 ChangeLog $DESTDIR/$PFIX/doc/alsa-utils/ChangeLog
	install -m 644 COPYING $DESTDIR/$PFIX/doc/alsa-utils/COPYING
}
