#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=1.7
PKG_SRCS=http://download.savannah.gnu.org/releases/lzip/clzip/clzip-$PKG_VER.tar.gz
PKG_DESC="A compression tool"
PKG_DEPS=musl

build() {
	./configure --prefix=/$PFIX \
	            --datarootdir=/$PFIX/share \
	            --mandir=/$PFIX/man \
	            CC=$CC \
	            CFLAGS="$CFLAGS" \
	            LDFLAGS="$LDFLAGS"
	[ $? -ne 0 ] && return 1

	$MAKE
}

package() {
	local i

	$MAKE install
	install -D -m 644 README $DESTDIR/$PFIX/doc/clzip/README
	for i in NEWS ChangeLog AUTHORS COPYING
	do
		install -m 644 $i $DESTDIR/$PFIX/doc/clzip/$i
	done

	ln -s clzip $DESTDIR/$PFIX/bin/lzip
	ln -s clzip.1 $DESTDIR/$PFIX/man/man1/lzip.1
}
