#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=6.3.26
PKG_SRCS=http://sourceforge.net/projects/fetchmail/files/branch_6.3/fetchmail-$PKG_VER.tar.xz
PKG_DESC="An e-mail retrieval tool"
PKG_DEPS="musl libressl"

build() {
	autoconf
	[ $? -ne 0 ] && return 1

	./configure --prefix=/$PFIX \
	            --mandir=/$PFIX/man \
	            --disable-nls \
	            --enable-fallback=no \
	            --with-ssl
	[ $? -ne 0 ] && return 1

	$MAKE
}

package() {
	local i

	install -D -m 755 fetchmail $DESTDIR/$PFIX/bin/fetchmail
	install -D -m 644 fetchmail.man $DESTDIR/$PFIX/man/man1/fetchmail.1
	install -D -m 644 README $DESTDIR/$PFIX/doc/fetchmail/README
	for i in FAQ NEWS COPYING
	do
		install -m 644 $i $DESTDIR/$PFIX/doc/fetchmail/$i
	done
}
