#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=4.07
PKG_SRCS=https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-$PKG_VER.tar.xz
PKG_DESC="A BIOS boot loader for ISO9660 file systems"

build() {
	cd syslinux-$PKG_VER
}

package() {
	install -D -m 644 core/isolinux.bin $DESTDIR/$PFIX/boot/isolinux.bin
	install -m 644 mbr/isohdpfx.bin $DESTDIR/$PFIX/boot/isohdpfx.bin
	install -m 644 com32/menu/menu.c32 $DESTDIR/$PFIX/boot/menu.c32
	install -D -m 644 README $DESTDIR/$PFIX/doc/isolinux/README
	install -m 644 NEWS $DESTDIR/$PFIX/doc/isolinux/NEWS
	install -m 644 COPYING $DESTDIR/$PFIX/doc/isolinux/COPYING
}
