#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=4.3
PKG_SRCS=https://www.kernel.org/pub/software/network/iw/iw-$PKG_VER.tar.xz
PKG_DESC="A wireless network interface configuration tool"
PKG_DEPS="musl libnl-tiny"

build() {
	# iw uses kernel-style sections that contain structs, so it breaks when
	# built with -gc-sections
	CFLAGS="-D_GNU_SOURCE $CFLAGS" \
	LDFLAGS="$(echo "$LDFLAGS" | sed s/-Wl,-gc-sections//)" \
	$MAKE
}

package() {
	$MAKE SBINDIR=/$PFIX/bin MANDIR=/$PFIX/man install
	install -D -m 644 README $DESTDIR/$PFIX/doc/iw/README
	install -m 644 COPYING $DESTDIR/$PFIX/doc/iw/COPYING
}
