#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_SRCS=https://git.openwrt.org/openwrt.git
PKG_DESC="An IPC library"
PKG_DEPS=musl

build() {
	local i

	cd package/libs/libnl-tiny/src

	for i in *.c
	do
		$CC $CFLAGS -Iinclude -c -o $(basename $i .c).o $i
	done

	ar rcs libnl-tiny.a *.o
	sed s~/usr~$DESTDIR/$PFIX~g -i ../files/libnl-tiny.pc

	head -n 9 socket.c | tail -n 6 | sed s/'^ \*\s*'//g > COPYING
}

package() {
	install -D -m 644 libnl-tiny.a $DESTDIR/$PFIX/lib/libnl-tiny.a
	mkdir -p $DESTDIR/$PFIX/include/libnl-tiny
	cp -a include/* $DESTDIR/$PFIX/include/libnl-tiny/
	install -D -m 644 \
	        ../files/libnl-tiny.pc \
	        $DESTDIR/$PFIX/lib/pkgconfig/libnl-tiny.pc
	install -D -m 644 COPYING $DESTDIR/$PFIX/doc/libnl-tiny/COPYING
}
