#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=2.3.3
PKG_SRCS=http://zlib.net/pigz/pigz-$PKG_VER.tar.gz
PKG_DESC="Compression tools"
PKG_DEPS="musl zlib"

package() {
	local i

	install -D -m 755 pigz $DESTDIR/$PFIX/bin/pigz
	ln -s pigz $DESTDIR/$PFIX/bin/gzip
	install -m 755 unpigz $DESTDIR/$PFIX/bin/unpigz
	ln -s unpigz $DESTDIR/$PFIX/bin/gunzip
	install -D -m 755 pigz.1 $DESTDIR/$PFIX/man/man1/pigz.1
	for i in unpigz gzip gunzip
	do
		ln -s pigz.1 $DESTDIR/$PFIX/man/man1/$i.1
	done
	install -D -m 644 README $DESTDIR/$PFIX/doc/pigz/README
	for i in README CONTRIBUTORS COPYING
	do
		install -m 644 zopfli/$i $DESTDIR/$PFIX/doc/pigz/$i.zopfli
	done
}
