#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_SRCS=https://github.com/tinyalsa/tinyalsa.git
PKG_DESC="Core audio library"
PKG_DEPS=musl

build() {
	CFLAGS="-D_BSD_SOURCE $CFLAGS" $MAKE libtinyalsa.a
}

package() {
	install -D -m 644 libtinyalsa.a $DESTDIR/$PFIX/lib/libtinyalsa.a
	install -D -m 644 README $DESTDIR/$PFIX/doc/tinyalsa/README
	head -n 26 mixer.c |
	tail -n 24 |
	cut -c 4- > $DESTDIR/$PFIX/doc/tinyalsa/COPYING
	chmod 644 $DESTDIR/$PFIX/doc/tinyalsa/COPYING
	cp -r include $DESTDIR/$PFIX/
}
