#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=7.47.1
PKG_SRCS=http://curl.haxx.se/download/curl-$PKG_VER.tar.bz2
PKG_DESC="A file transfer library"
PKG_DEPS="musl zlib libressl"

build() {
	./configure --prefix=/$PFIX \
	            --mandir=/$PFIX/man \
	            --enable-static \
	            --disable-shared \
	            --disable-debug \
	            --with-ca-bundle=/$PFIX/etc/ssl/cert.pem \
	            --disable-rtsp \
	            --enable-ipv6
	[ $? -ne 0 ] && return 1

	$MAKE
}

package() {
	local i

	$MAKE install
	install -D -m 644 README $DESTDIR/$PFIX/doc/curl/README
	for i in RELEASE-NOTES CHANGES COPYING
	do
		install -m 644 $i $DESTDIR/$PFIX/doc/curl/$i
	done
}

