#!/bin/sh

# this file is part of packlim-recipes.
#
# Copyright (c) 2016 Dima Krasner
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PKG_VER=5.2.2
PKG_SRCS=http://tukaani.org/xz/xz-$PKG_VER.tar.xz
PKG_DESC="Compression tools"
PKG_DEPS=musl

build() {
	./configure --prefix=/$PFIX \
	            --includedir=/$PFIX/include \
	            --datarootdir=/$PFIX \
	            --enable-static \
	            --disable-shared \
	            --disable-xzdec \
	            --disable-lzmadec \
	            --disable-scripts \
	            --disable-nls
	[ $? -ne 0 ] && return 1

	$MAKE
}

package() {
	local i

	$MAKE install
	for i in ChangeLog COPYING.GPLv3
	do
		install -m 644 $i $DESTDIR/$PFIX/doc/xz/$i
	done
}
